spring:
  application:
    name: rest-with-spring-boot-and-java-almeida
  datasource:
    url: jdbc:mysql://localhost:3307/rest_with_spring_boot_almeida_db?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: vani1010
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: false
    open-in-view: false